language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-15
    - extra-android-support
    
jdk: oraclejdk7

notifications:
  email: false

before_install:
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod +x android-ndk-r10e-linux-x86_64.bin && ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - mv android-ndk-r10e android-ndk
  - export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
  - git clone -q --depth=1 https://github.com/SDLash3D/xash3d jni/src/Xash3D/xash3d
  - git clone -q --depth=1 https://github.com/SDLash3D/halflife jni/src/HLSDK/halflife
  - git clone -q --depth=1 https://github.com/SDLash3D/MobileTouchControls jni/src/MobileTouchControls/MobileTouchControls
  - git clone -q --depth=1 https://github.com/SDLash3D/nanogl jni/src/NanoGL/nanogl
  - git clone -q --depth=1 https://github.com/SDLash3D/XashXT jni/src/XashXT/XashXT
  - git clone -q --depth=1 https://github.com/mittorn/SDL-mirror jni/src/SDL2/SDL-mirror
  - sed -i -- s/android-8/android-15/g project.properties
script:
  - sh gen-version.sh travis build
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-armv7.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="armeabi"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-armv6.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="x86"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-x86.apk
after_script:
  - curl --upload-file xashdroid-armv7.apk https://transfer.sh/xash3d-armv7-`date -u +%y-%m-%d_%H-%M`.apk
  - curl --upload-file xashdroid-armv6.apk https://transfer.sh/xash3d-armv6-`date -u +%y-%m-%d_%H-%M`.apk
  - curl --upload-file xashdroid-x86.apk https://transfer.sh/xash3d-x86-`date -u +%y-%m-%d_%H-%M`.apk
  - curl -T bin/xashdroid-armv7.apk -u $YADISK_USERNAME:$YADISK_PASSWORD https://webdav.yandex.ru/XashTestVersions/xashdroid-armv7-`date -u +%y-%m-%d_%H-%M`-`git rev-parse --short HEAD`.apk
  - curl -T bin/xashdroid-armv6.apk -u $YADISK_USERNAME:$YADISK_PASSWORD https://webdav.yandex.ru/XashTestVersions/xashdroid-armv6-`date -u +%y-%m-%d_%H-%M`-`git rev-parse --short HEAD`.apk
  - curl -T bin/xashdroid-x86.apk -u $YADISK_USERNAME:$YADISK_PASSWORD https://webdav.yandex.ru/XashTestVersions/xashdroid-x86-`date -u +%y-%m-%d_%H-%M`-`git rev-parse --short HEAD`.apk
  