language: c
cache: ccache
compiler: gcc
sudo: false
addons:
  apt:
    packages:
      - mingw-w64-i686-dev
      - binutils-mingw-w64-i686
      - gcc-mingw-w64-i686
      - g++-mingw-w64-i686
      - p7zip-full
      - gcc-multilib
      - g++-multilib
      - libx11-dev:i386
      - libxext-dev:i386
      - x11-utils
      - libgl1-mesa-dev
      - libasound-dev
      - zlib1g:i386
      - libstdc++6:i386
env:
  global:
    - SDL_VERSION=2.0.8
git:
  depth: 50
  submodules: true
jdk:
  - oraclejdk8
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
before_script:
  - sh scripts/travis_common_deps.sh
  - sh scripts/travis_${TRAVIS_OS_NAME}_deps.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ANDROID_HOME=$PWD/android-sdk-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PWD/android-ndk; fi
script:
  - sh scripts/build_${TRAVIS_OS_NAME}_engine.sh
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_android_engine.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_mingw_engine.sh; fi
