language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-13
    - extra-android-support
    
jdk: oraclejdk7

notifications:
  email: false

before_install:
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod +x android-ndk-r10e-linux-x86_64.bin && ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - mv android-ndk-r10e android-ndk
  - export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
  - git submodule init 
  - git submodule update
script:
  - sh gen-version.sh travis build
  - sh gen-config.sh test
  - python2 makepak.py xash-extras assets/extras.pak
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-stub.apk
